/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./components/Breadcrumb/index.vue')['default']
    Editor: typeof import('./components/Editor/index.vue')['default']
    EditorImage: typeof import('./components/Tinymce/components/EditorImage.vue')['default']
    Hamburger: typeof import('./components/Hamburger/index.vue')['default']
    HeaderSearch: typeof import('./components/HeaderSearch/index.vue')['default']
    IconSelect: typeof import('./components/IconSelect/index.vue')['default']
    KyTinymce: typeof import('./components/KyTinymce/index.vue')['default']
    MDinput: typeof import('./components/MDinput/index.vue')['default']
    Pagination: typeof import('./components/Pagination/index.vue')['default']
    RightPanel: typeof import('./components/RightPanel/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Screenfull: typeof import('./components/Screenfull/index.vue')['default']
    SingleImage: typeof import('./components/Upload/SingleImage.vue')['default']
    SizeSelect: typeof import('./components/SizeSelect/index.vue')['default']
    Sticky: typeof import('./components/Sticky/index.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
    ThemePicker: typeof import('./components/ThemePicker/index.vue')['default']
    Tinymce: typeof import('./components/Tinymce/index.vue')['default']
  }
}
